version: '3.7'

services:
  bun:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/home/bun/app
    ports:
      - 3333:3333

  postgres:
    image: bitnami/postgresql:latest
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=pizzashop
    volumes:
      - postgres_data:/bitnami/postgresql

volumes:
  postgres_data:
